# It needs to define this macro to use TOPPERS/JSP
TOPPERS_KERNEL = NXT_JSP
BUILD_MODE = ROM_ONLY

# Target specific macros
TARGET = eval_JSP
TARGET_SOURCES = \
	eval.c
USER_INC_PATH = ./NXT
USER_DEF = ONLINE IRCOM LISTLIB FLOAT NXT OSEK
#USER_DEF = JOINT RCX TOPPERS BALANCE
TOPPERS_JSP_CFG_SOURCE = ./NXT/eval.cfg

eval.o : eval.c NXT/eval-debug.h NXT/eval-task.c

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
